after_success: 
  - "npm run coverage"
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - stable
install:
- npm install
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE freeMentors;' -U postgres
notifications: 
  email: false
script: 
  - "npm run test"
sudo: false