
const REQUEST_SUCCEDED = 200;
const RESOURCE_CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const REQUEST_TIMEOUT = 408;
const REQUEST_CONFLICT = 409;
const SERVER_ERROR = 500;
const SERVICE_UNAVAILABLE = 503;

export {
  REQUEST_SUCCEDED, RESOURCE_CREATED,
  BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND,
  REQUEST_TIMEOUT, REQUEST_CONFLICT, SERVER_ERROR,
  SERVICE_UNAVAILABLE,
};
